# Generated by Django 3.2.8 on 2021-11-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='autor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
